<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bot</string>
		<string>botl</string>
	</array>
	<key>name</key>
	<string>BotL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.BotL</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>require declaration</string>
			<key>match</key>
			<string>(require)\s+(".*")</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>declaration predicates</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.BotL</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.BotL</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(report|function|externally_called) ([a-zA-Z0-9_]+)(/{0,1}[0-9]{0,});</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z][a-zA-Z0-9_!]{0,})(\({0,1})([^\)]{0,})(\){0,1})\s{0,}(&lt;--)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>predicate definitions (with body)</string>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#trivial-predicates</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#el-database</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-calls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#globals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbols</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>predicate definitions (no body)</string>
			<key>match</key>
			<string>^([a-zA-Z][a-zA-Z0-9_!]{0,})(\({0,1})([^\)]{0,})(\){0,1});</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.{0,}</string>
					<key>name</key>
					<string>comment.line.double-slash</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
		<key>el-database</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>@</string>
					<key>name</key>
					<string>constant.character</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([/:])([a-zA-Z][a-zA-Z0-9_\$]+)</string>
					<key>name</key>
					<string>constant.language.BotL</string>
				</dict>
			</array>
		</dict>
		<key>function-calls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-zA-Z][a-zA-Z0-9_!]+)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#el-database</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#symbols</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#globals</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>globals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)([a-zA-Z0-9_]+)</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[0-9]</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>symbols</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[a-z][a-zA-Z0-9_!]{0,}</string>
					<key>name</key>
					<string>constant.other</string>
				</dict>
			</array>
		</dict>
		<key>trivial-predicates</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>true|fail|!|set!</string>
					<key>name</key>
					<string>constant.language.BotL</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;|&gt;|=|+|-|*|/</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Z][a-zA-Z0-9_]{0,}</string>
					<key>name</key>
					<string>variable.language</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.BotL</string>
	<key>uuid</key>
	<string>1169e5a0-097a-413d-a634-9fde39949713</string>
</dict>
</plist>
